name: Feature request
description: Suggest an idea for this project
title: "[Feature]: "
labels: ["feature"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to propose idea and to contribute to the project.
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: A clear and concise description of what the feature is.
    validations:
      required: true
  - type: textarea
    id: alternative
    attributes:
      label: Alternative
      description: A description of alternative solutions or features you've considered.
  - type: textarea
    id: draft
    attributes:
      label: Draft
      description: Write a proposal for the feature, how it works, its expected coverage, a sample code or unit test. If the feature is related to a documentation or article, write the content or the table of content you expect.
  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request here.
